# @package core_lib
bitbucket_core_lib:
    base_url: ${oc.env:BITBUCKET_API_BASE_URL,"https://api.bitbucket.org/2.0"}
    token: ${oc.env:BITBUCKET_API_TOKEN,""}
    username: ${oc.env:BITBUCKET_USERNAME,""}
    api_email: ${oc.env:BITBUCKET_API_EMAIL,""}
    workspace: ${oc.env:BITBUCKET_WORKSPACE,""}
    repo_slug: ${oc.env:BITBUCKET_REPO_SLUG,""}
    assignee: ${oc.env:BITBUCKET_ASSIGNEE,""}
    max_retries: ${oc.decode:${oc.env:BITBUCKET_CORE_LIB_MAX_RETRIES,"3"}}
