# @package core_lib
jira_core_lib:
    base_url: ${oc.env:JIRA_API_BASE_URL,"https://your-company.atlassian.net"}
    token: ${oc.env:JIRA_API_TOKEN,""}
    email: ${oc.env:JIRA_EMAIL,""}
    project: ${oc.env:JIRA_PROJECT,""}
    assignee: ${oc.env:JIRA_ASSIGNEE,""}
    max_retries: ${oc.decode:${oc.env:JIRA_CORE_LIB_MAX_RETRIES,"3"}}
